[book]
authors = ["drpaneas"]
language = "en"
multilingual = false
src = "docs" # <- this is where the markdown files should be
title = "PIGO8 Documentation"
description = "Technical reference for the PIGO8 library to help you make PICO-8 games using Go."

[build]
build-dir = "book" # <- default and expected by GH Actions. No need to create thid folder, Github will do.