name: goreleaser

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions: # Add this block
  contents: write
  actions: read

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important: this fetches all history for tags and commits needed by GoReleaser

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Set up xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
        env:
          DISPLAY: ":99"

      - name: Start xvfb
        run: Xvfb :99 -screen 0 1024x768x24 &

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libc6-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, no need to create a new one